//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVM.Paginas.Admin {
    
    
    public partial class ReportesCuestionario {
        
        /// <summary>
        /// contReportesCuestionarioMedico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AVM.Controles.Admin.contReportesCuestionarioMedico contReportesCuestionarioMedico;
        
        /// <summary>
        /// contReportesCuestionarioDental control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AVM.Controles.Admin.contReportesCuestionarioDental contReportesCuestionarioDental;
        
        /// <summary>
        /// contReportesCuestionarioPsicologico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AVM.Controles.Admin.contReportesCuestionarioPsicologico contReportesCuestionarioPsicologico;
    }
}
